name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.NANAYEYARDOCKERHUB_USERNAME }}
          password: ${{ secrets.NANAYEYARDOCKERHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: |
          SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
          echo "date_tag=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            ${{ secrets.NANAYEYARDOCKERHUB_USERNAME }}/nan-ayeyar-api:latest
            ${{ secrets.NANAYEYARDOCKERHUB_USERNAME }}/nan-ayeyar-api:${{ steps.vars.outputs.sha_short }}

      - name: Build and push Admin
        uses: docker/build-push-action@v5
        with:
          context: ./apps/admin
          file: ./apps/admin/Dockerfile
          push: true
          tags: |
            ${{ secrets.NANAYEYARDOCKERHUB_USERNAME }}/nan-ayeyar-admin:latest
            ${{ secrets.NANAYEYARDOCKERHUB_USERNAME }}/nan-ayeyar-admin:${{ steps.vars.outputs.sha_short }}

      - name: Build and push Ecommerce
        uses: docker/build-push-action@v5
        with:
          context: ./apps/ecommerce
          file: ./apps/ecommerce/Dockerfile
          push: true
          tags: |
            ${{ secrets.NANAYEYARDOCKERHUB_USERNAME }}/nan-ayeyar-ecommerce:latest
            ${{ secrets.NANAYEYARDOCKERHUB_USERNAME }}/nan-ayeyar-ecommerce:${{ steps.vars.outputs.sha_short }}


